version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform

  pre_build:
    commands:
      - cd terraform-modules/infrastructure
      - terraform init
      
  
  build:
    commands:
      - ls
      - terraform plan -out=plan.tfplan
      # - terraform apply plan.tfplan -auto-approve
    