version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - cd react-app
      - npm install

  pre_build:
    commands:
      - ASSUME_ROLE_ARN="arn:aws:iam::778196150762:role/TerraformInCodeBuild"
      - ROLE_CREDENTIALS=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name CodeBuildDeployReactApp)
      - export AWS_ACCESS_KEY_ID=$(echo "${ROLE_CREDENTIALS}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${ROLE_CREDENTIALS}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${ROLE_CREDENTIALS}" | jq -r '.Credentials.SessionToken')
      
  build:
    commands:
      - npm run build
      - aws s3 rm s3://ajdt.dev --recursive
      - aws s3 cp --recursive ./dist s3://ajdt.dev

  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E2R31D6X9IWNWU --paths "/*"
    